In [1]:
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Vectors

## Practical 

Calculate the absolute difference between the sum of squared numbers between 1 and 100 and the square of their sum, once in pure python and with numpy arrays: 
$$ |(1^2 + 2^2 + 3^2 + ...) - (1 + 2 + 3 + ...)^2|$$ 


### Pure python:

First solution:

In [37]:
mylist = list(range(1, 101))
Squarelist = []
Sumlist = 0
sumSquarelist = 0
for i in range(len(mylist)):
    Squarelist.append(mylist[i]*mylist[i])
    sumSquarelist = sumSquarelist + Squarelist[i]
    Sumlist = Sumlist + mylist[i]
print(-(sumSquarelist - Sumlist**2))

25164150


Second solution:

In [38]:
squared = sum([i**2 for i in range(1,101)])
square = sum(range(1,101))**2
difference = abs(squared - square)
print(difference)

25164150


Third solution:

In [46]:
def diff(n):
    s1 = 0
    s2 = 0
    for i in range(n+1):
        s1 = s1+ i**2
        s2 = (i*(i+1)/2)**2
    s3 = s1-s2;
    return(abs(s3))
%timeit diff(100)

9.18 µs ± 47.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Numpy array

First solution:

In [44]:
nums = np.arange(1,101)
sq_sum = np.square(np.sum(nums))
sum_sq = np.sum(np.square(nums))
diff = np.abs(sum_sq - sq_sum)
diff

25164150

Second solution:

In [51]:
def operation1():
    b = np.arange(1, 101)
    return np.abs(np.sum(b**2) - (np.sum(b))**2)
%timeit operation1()

4.11 µs ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Third solution:

In [50]:
def operation():
    a = np.arange(1, 101)
    return np.abs(np.sum(np.square(a)) - np.square((np.sum(a))))
%timeit operation()

4.49 µs ± 26.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Practical: Finding the biggest product

In the 20×20 grid below, four numbers along a diagonal line have been marked in red.

<img src="../assets/number.png" alt="" width="500"/>

The product of these numbers is 26 × 63 × 78 × 14 = 1788696.

What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20×20 grid?

### Potential approach
1. Getting the numbers in a workable format - (from string to integers, in a list, etc)
2. Writing a loop to extract a 4x4 matrix of the grid
3. Writing a function to calculate all potential products

In [53]:
num = ("""
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48""".replace("\n", " "))

## Answer:

First solution:

In [55]:
A = np.reshape([int(x) for x in num.split()], (20,20))
A

array([[ 8,  2, 22, 97, 38, 15,  0, 40,  0, 75,  4,  5,  7, 78, 52, 12,
        50, 77, 91,  8],
       [49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48,
         4, 56, 62,  0],
       [81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30,  3,
        49, 13, 36, 65],
       [52, 70, 95, 23,  4, 60, 11, 42, 69, 24, 68, 56,  1, 32, 56, 71,
        37,  2, 36, 91],
       [22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28,
        66, 33, 13, 80],
       [24, 47, 32, 60, 99,  3, 45,  2, 44, 75, 33, 53, 78, 36, 84, 20,
        35, 17, 12, 50],
       [32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66,
        18, 38, 64, 70],
       [67, 26, 20, 68,  2, 62, 12, 20, 95, 63, 94, 39, 63,  8, 40, 91,
        66, 49, 94, 21],
       [24, 55, 58,  5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88,
        34, 89, 63, 72],
       [21, 36, 23,  9, 75,  0, 76, 44, 20, 45, 35, 14,  0, 61, 33, 97,
        34, 31, 33, 95],
       [78, 17, 53, 28, 22, 75

In [60]:
B = A[0:4,0:4]
B

array([[ 8,  2, 22, 97],
       [49, 49, 99, 40],
       [81, 49, 31, 73],
       [52, 70, 95, 23]])

In [66]:
np.prod(B,axis=1)

array([  34144, 9507960, 8981847, 7953400])

In [64]:
n = np.shape(A)[0]
m = np.shape(A)[1]

def product_max(B):
    max2 = np.max(np.prod(B,axis=1))
    max2 = np.maximum(max2, np.max(np.max(B,axis=0)))
    max2 = np.maximum(max2, B[0,0] * B[1,1] * B[2,2] * B[3,3])
    max2 = np.maximum(max2, B[3,0] * B[2,1] * B[1,2] * B[0,3])
    return max2

max1 = np.max(A[0, 0:4])

for i in range(n-3):
    for j in range(m-3):
        max1 = np.maximum(max1, product_max(A[i:i+4, j:j+4]))
print(max1)

70600674


Second solution:

In [73]:
#assuming we can not use reshape
data=np.array([int(x) for x in num.strip().split(' ')])
dim=int(np.sqrt(len(data)))
results=[]
for i in range(0, dim-3):
    for j in range(0, dim-3):
        h=1
        v=1
        d=1
        d2=1
        for k in range(0, 4):
            h *= data[i * dim + j + k]
            v *= data[(i + k) * dim + j]
            d *= data[(i + k) * dim + j + k]
            d2 *= data[(i + k) * dim + j + 3 - k]
        results.append([h, v, d, d2])
res=np.array(results)
print(np.amax(res))

70600674


In [74]:
res.shape

(289, 4)

In [76]:
len(results)

289

In [70]:
17 * 17

289

In [71]:
17 * 17 * 4

1156

Note: the last 3 rows and 3 columns are not included in the above calculation. This should be added to the above solution.

Third solution:

In [79]:
def question1(num):

    # Function to create product of numbers 
    def list_product(digits, maximum):
        # Calculating the maximum of left, right, up and down
        for i in range(digits.shape[0]):
            product = max(np.prod(digits[:,i]), # Horizontal
                          np.prod(digits[i,:]), # Vertical
                          np.prod(digits.diagonal()), # Diagonal
                          np.prod(np.fliplr(digits).diagonal()) # Reverse diagonal
                          )        
            # Checking whether its higher than the maximum
            if product > maximum:
                maximum = product

        return maximum

    # Length of the number of rows
    num_rows = 20
    adjacent_numbers = 4
    max_product = 0

    # List out of all numbers
    list_num = num.split()

    # Empty list 
    list_lists = []

    # Numpy list of lists - Changing the format from the a big list, to a list of lists
    for elem in range(num_rows):
        start = (elem) * 20 # The grid has 20 columns
        end = (elem + 1) * 20 
        row = list_num[start:end]
        list_lists.append(row)    

    # Using numpy for easier slicing
    list_lists = np.array(list_lists, dtype = int) # This is used for using the functions with less effort

    # Getting 4x4 matrices out of all the datapoints
    for i in range(num_rows - adjacent_numbers):
        # Going column wise 
        start_i = i
        end_i = i + 4
        # As well as row wise
        for j in range(num_rows - adjacent_numbers):
            start_j = j
            end_j = j + 4
            # Applying the function for every 4x4 matrix
            max_product = list_product(list_lists[start_i:end_i,start_j:end_j],
                                       max_product)

    print(max_product)
    
question1(num)

70600674
