In [2]:
import pickle 
import numpy as np

# Matrices

## Practical

Aggregate by variance `np.var` 
- over the rows
- over the columns
- over all data

In [29]:
np.var(data, axis=0)

array([0.00760577, 0.0457996 , 0.01004362])

In [30]:
np.var(data, axis=1)

array([0.03707446, 0.08028754])

In [31]:
np.var(data)

0.0765867744040815

## Matrix Practice

1. Write a function (using numpy) to sort a given array of shape 2 along the first axis (rows), second axis (column), and on a flattened array.

example: 

In [54]:
# Expected Output:
# Original array:
np.array([[10, 40],
          [30, 20]])
# Sort the array along the first axis:
np.array([[10, 20],
          [30, 40]])
# Sort the array along the last axis:
np.array([[10, 40],
          [20, 30]])
# Sort the flattened array:
np.array([10, 20, 30, 40])

array([10, 20, 30, 40])

#### Answer:

In [55]:
# original array
a = np.array([[10, 40],
          [30, 20]])
print("Original Array:", a)

print("Sort the array along the first axis (rows):")
print(np.sort(a, axis=0))

print("Sort the array along the last axis (columns):")
print(np.sort(a, axis=1))

print("Sort the flattened array:")
print(np.sort(a, axis=None))

Original Array: [[10 40]
 [30 20]]
Sort the array along the first axis (rows):
[[10 20]
 [30 40]]
Sort the array along the last axis (columns):
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


2. Write a function to get the indices of the sorted elements of a given array

Expected Output:

Original array:


`[1023 5202 6230 1671 1682 5241 4532]`


Indices of the sorted elements of a given array:


`[0 3 4 6 1 5 2]`

#### Answer

In [56]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
def id_sorter(id_array):
    print("Original Array:")
    print(id_array)
    i = np.argsort(student_id)
    print("Indicies of the sorted elements of student ID array:")
    print(i)
    return i 

id_sorter(student_id)


Original Array:
[1023 5202 6230 1671 1682 5241 4532]
Indicies of the sorted elements of student ID array:
[0 3 4 6 1 5 2]


array([0, 3, 4, 6, 1, 5, 2])

3. Write a function to create a 5x5 array with random values and find the minimum and maximum values.

#### Answer

In [57]:
def rand5_min_max():
    x = np.random.random((5,5))
    print("Original Array:")
    print(x) 
    xmin, xmax = x.min(), x.max()
    print("Minimum and Maximum Values:")
    print(xmin, xmax)
    return xmin, xmax

rand5_min_max()

Original Array:
[[0.10692117 0.77249894 0.26497063 0.20244497 0.3627213 ]
 [0.68652303 0.15103275 0.05835538 0.74999069 0.98601996]
 [0.89658771 0.87459671 0.92502281 0.93525835 0.53746398]
 [0.83605902 0.69589308 0.92224564 0.81938786 0.96665166]
 [0.0116458  0.18240519 0.87470089 0.92294342 0.78609639]]
Minimum and Maximum Values:
0.011645796360233773 0.986019958230802


(0.011645796360233773, 0.986019958230802)