In [1]:
import pickle 
import numpy as np

# Matrices

In [3]:
data = np.random.rand(2, 3)
data

array([[0.41355382, 0.03883608, 0.40575421],
       [0.2897562 , 0.31028894, 0.7556762 ]])

## Practical

Aggregate by variance `np.var` 
- over the rows
- over the columns
- over all data

In [6]:
# over the rows
print(data.var(axis=1))
# over the cols
print(data.var(axis=0))
# over all data
print(data.var())

[0.00676872 0.02421247]
[1.31537198e-02 1.13920991e-05 3.53144670e-03]
0.01587265004572448


## Matrix Practice

1. Write a function (using numpy functions) to sort a given array of shape 2 along the first axis (rows), second axis (column), and on a flattened array.

example: 

In [ ]:
# Expected Output:
# Original array:
np.array([[10, 40],
          [30, 20]])
# Sort the array along the first axis:
np.array([[10, 20],
          [30, 40]])
# Sort the array along the last axis:
np.array([[10, 40],
          [20, 30]])
# Sort the flattened array:
np.array([10, 20, 30, 40])

#### Answer:

In [10]:
A = np.array([[50, 40],
          [30, 20]])
sort1 = np.sort(A, axis = 0)
sort2 = np.sort(A, axis = 1)
sort3 = np.sort(A.flatten())
print(sort1)
print(sort2)
print(sort3)

[[30 20]
 [50 40]]
[[40 50]
 [20 30]]
[20 30 40 50]


2. Write a function (using numpy functions) to get the indices of the sorted elements of a given array

Expected Output:

Original array:


`[1023 5202 6230 1671 1682 5241 4532]`


Indices of the sorted elements of a given array:


`[0 3 4 6 1 5 2]`

#### Answer

In [11]:
b = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
def ind_sort(ind_array):
    print("Original array:" )
    print(ind_array)
    i = np.argsort(b)
    print("Indices of the sorted elements of a given array:")
    print(i)
    return i
ind_sort(b)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


array([0, 3, 4, 6, 1, 5, 2])

3. Write a function (using numpy functions) to create a 5x5 array with random values and find the minimum and maximum values.

#### Answer

In [12]:
import random
nums = np.array(random.sample(range(1, 100), 25)).reshape(5, 5)
max = np.amax(nums)
min = np.amin(nums)
print(nums)
print(max,min)

[[48 81 30 84 52]
 [20 62 26 96  8]
 [69 66 13  3 33]
 [47 19 94 95  4]
 [79 65 86 51 22]]
96 3


Second solution:

In [14]:
def max_min(n):
    k=np.random.rand(n,n)
    a=k.flatten()
    print(a)
    z=np.max(a)
    y=np.min(a)
    print("The max is =", z, "The min is =", y)
max_min(5)

[0.15663727 0.62336892 0.70946806 0.91593103 0.27884586 0.90280829
 0.69365238 0.76775713 0.85169869 0.90682757 0.96920275 0.14910676
 0.45736915 0.4898485  0.54356277 0.99913221 0.47419099 0.76341164
 0.57550112 0.2147794  0.30327251 0.51554358 0.86074812 0.33312791
 0.80563653]
The max is = 0.9991322117471065 The min is = 0.149106762102598
